---
name: Class-InsideOut
version: 0.09
author:
  - David A. Golden <dagolden@cpan.org>
abstract: 'a safe, simple inside-out object construction kit'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::ISA: 0
  Config: 0
  Exporter: 0
  Scalar::Util: 1.09
  Test::More: 0.48
  base: 0
  perl: 5.005
provides:
  Class::InsideOut:
    file: lib/Class/InsideOut.pm
    version: 0.09
generated_by: Module::Build version 0.2703
