---
name: Class-InsideOut
version: 0.15_01
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: 'a safe, simple inside-out object construction kit'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::ISA: 0
  Config: 0
  Exporter: 0
  Scalar::Util: 1.09
  Test::More: 0.45
  base: 0
  perl: 5.005
provides:
  Class::InsideOut:
    file: lib/Class/InsideOut.pm
    version: 0.15_01
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  file:
    - lib\Class\InsideOut\Manual\About.pm
    - lib\Class\InsideOut\Manual\Advanced.pm
