---
name: Class-InsideOut
version: 1.10
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: 'a safe, simple inside-out object construction kit'
license: apache
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
requires:
  Class::ISA: 0
  Config: 0
  Exporter: 0
  Scalar::Util: 1.09
  Test::More: 0.45
  base: 0
  perl: 5.005
configure_requires:
  Module::Build: 0.34
provides:
  Class::InsideOut:
    file: lib/Class/InsideOut.pm
    version: 1.10
  Class::InsideOut::Manual::About:
    file: lib/Class/InsideOut/Manual/About.pm
    version: 1.10
  Class::InsideOut::Manual::Advanced:
    file: lib/Class/InsideOut/Manual/Advanced.pm
    version: 1.10
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - examples
  file:
    - lib/Class/InsideOut/Manual/About.pm
    - lib/Class/InsideOut/Manual/Advanced.pm
